# Generated by Django 4.0.5 on 2022-06-20 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_content', models.CharField(max_length=100)),
                ('title_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_content', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.FileField(upload_to='')),
                ('videos_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.title_content')),
            ],
        ),
    ]
