# Generated by Django 4.0.5 on 2022-06-20 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_title_content_videos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title_content',
            old_name='title_add',
            new_name='title_videos',
        ),
        migrations.RenameField(
            model_name='videos',
            old_name='video_name',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='videos',
            old_name='videos_add',
            new_name='videos_title',
        ),
    ]
