# Generated by Django 4.0.3 on 2022-06-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_title_add_title_content_title_videos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='video_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
