# Generated by Django 4.0.3 on 2022-06-20 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_videos_video_name_alter_videos_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='video',
            new_name='videos',
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons_name', models.CharField(max_length=100)),
                ('lessons_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
            ],
        ),
        migrations.AlterField(
            model_name='videos',
            name='videos_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.lessons'),
        ),
        migrations.DeleteModel(
            name='Title_content',
        ),
    ]
